package com.tourgether.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    // global
    NOT_FOUND(404, "COMMON-ERR-404", "PAGE NOT FOUND"),
    INTER_SERVER_ERROR(500, "COMMON-ERR-500", "INTER SERVER ERROR"),

    // member
    MEMBER_NOT_FOUND(400, "MEMBER-ERR-400", "MEMBER NOT FOUND"),
    EMAIL_DUPLICATION(400, "MEMBER-ERR-400", "EMAIL DUPLICATED"),
    NICKNAME_DUPLICATION(400, "MEMBER-ERR-400", "NICKNAME DUPLICATED"),
    PASSWORD_MISMATCH(400, "MEMBER-ERR-400", "PASSWORD DO NOT MATCH"),
    PASSWORD_SAME(400, "MEMBER-ERR-400", "PASSWORD SAME WITH ORIGINAL"),

    // notification
    NOTIFICATION_NOT_FOUND(400, "NOTIFICATION-ERR-400", "NOTIFICATION NOT FOUND"),

    // recruit
    RECRUIT_NOT_FOUND(400, "RECRUIT-ERR-400", "RECRUITMENT NOT FOUND"),
    COMMENT_NOT_FOUND(400, "COMMENT-ERR-400", "COMMENT NOT FOUND"),
    WRITER_MISMATCH(400, "RECRUIT-ERR-400", "WRITER DO NOT MATCH"),
    KEYWORD_NOT_ENTERED(400, "RECRUIT-ERR-400", "KEYWORD NOT ENTERED"),

    // chat
    CHAT_NOT_FOUND(400, "CHATTING-ERR-400", "CHAT NOT FOUND"),
    CHATROOM_NOT_FOUND(400, "CHATROOM-ERR-400", "CHATROOM NOT FOUND"),

    // bookmark
    BOOKMARK_NOT_FOUND(400, "BOOKMARK-ERR-400", "BOOKMARK NOT FOUND"),

    // apply
    APPLY_NOT_FOUND(400, "APPLY-ERR-400", "APPLY NOT FOUND"),
    ACCEPTANCE_NOT_INSERTED(400, "APPLY-ERR-400", "ACCEPTANCE_NOT_INSERTED");

    private final int status;
    private final String code;
    private final String message;
}
